### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [simplegametutorials/simplegametutorials.github.io#2]
I see you have no LICENSE for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later or Apache-2.0 license so that others are encouraged to contribute changes back to your project.

**Comment by hahawoo** [comment]
Thanks for the suggestion, I've added the [CC0 LICENSE](https://github.com/simplegametutorials/simplegametutorials.github.io/blob/master/LICENSE).
